
# ---- Base Node image ----
FROM node:18-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

# Copy Prisma schema BEFORE prisma generate
COPY prisma ./prisma

# Generate Prisma Client
RUN npx prisma generate

# Copy all NestJS source
COPY . .

# Build NestJS
RUN npm run build

EXPOSE 3000

CMD ["node", "dist/main.js"]
